### ISSUE TITLE
Unable to run npm shrinkwrap with redux-async-connect

### ISSUE THREAD

**Issue by veeracs** [Rezonans/redux-async-connect#29]
⚡ npm shrinkwrap
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/csekharveera/.nvm/versions/node/v4.2.5/bin/node" "/Users/csekharveera/.nvm/versions/node/v4.2.5/bin/npm" "shrinkwrap"
npm ERR! node v4.2.5
npm ERR! npm  v2.14.12

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: history@1.17.0 /Users/csekharveera/Sites/app-f-vertical/node_modules/redux-async-connect/node_modules/history
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/csekharveera/Sites/app-f-vertical/npm-debug.log

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/Users/csekharveera/.nvm/versions/node/v4.2.5/bin/node',
1 verbose cli   '/Users/csekharveera/.nvm/versions/node/v4.2.5/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@2.14.12
3 info using node@v4.2.5
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack extraneous: history@1.17.0 /Users/csekharveera/Sites/app-f-vertical/node_modules/redux-async-connect/node_modules/history
4 verbose stack     at shrinkwrap_ (/Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/lib/shrinkwrap.js:37:15)
4 verbose stack     at /Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/lib/shrinkwrap.js:31:5
4 verbose stack     at /Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/lib/ls.js:47:30
4 verbose stack     at /Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
4 verbose stack     at /Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
4 verbose stack     at cb (/Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
4 verbose stack     at cb (/Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
4 verbose stack     at cb (/Users/csekharveera/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
5 verbose cwd /Users/csekharveera/Sites/app-f-vertical
6 error Darwin 14.5.0
7 error argv "/Users/csekharveera/.nvm/versions/node/v4.2.5/bin/node" "/Users/csekharveera/.nvm/versions/node/v4.2.5/bin/npm" "shrinkwrap"
8 error node v4.2.5
9 error npm  v2.14.12
10 error Problems were encountered
10 error Please correct and try again.
10 error extraneous: history@1.17.0 /Users/csekharveera/Sites/app-f-vertical/node_modules/redux-async-connect/node_modules/history
11 error If you need help, you may report this error at:
11 error     https://github.com/npm/npm/issues
12 verbose exit [ 1, true ]

**Comment by sars** [comment]
hi @veeracs 
please send your package.json

**Comment by veeracs** [comment]
hi @sars, sorry for late response, I gave up on redux async connect. Please close this ticket, if I happen to use async connect in the future and not be able to shrinkwrap, I'll get back to you. Thank you for your time.
